name: bade_wangsul
description: Platform mobile untuk izin kepulangan santri di pondok pesantren.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  uuid: ^3.0.2
  formz: ^0.4.0-nullsafety.0

  firebase_core: ^1.0.1
  google_sign_in: ^5.0.1
  google_fonts: ^2.0.0
  cloud_firestore: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_crashlytics: ^1.0.0

  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.5
  image_picker: ^0.7.3
  path_provider: ^2.0.1
  sembast: ^3.0.0+4

  pdf: ^3.1.0
  flutter_pdfview: ^1.0.4
  printing: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/