name: bade_wangsul
description: Platform mobile untuk izin kepulangan santri di pondok pesantren.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.2
  equatable: ^1.0.2
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.4
  formz: ^0.3.0
  google_fonts: ^1.1.2
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.0+1
  font_awesome_flutter: ^8.11.0
  shared_preferences: ^0.5.12+4
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22

  path_provider: ^1.6.27
  sembast: ^2.4.9



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true